server:
  port: 8080

#spring:
#  data:
#    couchbase:
#      auto-index: true


springdoc:
  swagger-ui:
    custom: true
    path: '/swagger-ui.html'

application:
  db:
    username: Administrator
    password: password
    bucket-name: default